server:
    port: 8003
spring:
    application:
        name: SUBSCRIPTION_API_GATEWAY

    cloud:
        gateway:
            routes:
            - id: SUBSCRIBER-SERVICE
              uri: 
                lb://SUBSCRIBER-SERVICE
              predicates: 
              - Path=/subscription/subscriber/**
              
            - id: PLAN-SERVICE
              uri: 
                lb://PLAN-SERVICE
              predicates: 
              - Path=/subscription/plans/**
